on:
  push:
    branches:
      - 'releases'

jobs:
  gather-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: badges
      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Update files
        run: |
          if [ -f /tmp/coverage.svg ]; then
              mv /tmp/coverage.svg badges/
          fi
          if [ -f /tmp/interrogate_badge.svg ]; then
              mv /tmp/interrogate_badge.svg badges/
          fi
      - name: Commit & push data
        run: |
          git add -f badges/*
          git commit -m "Record badges [$(date +'%Y-%m-%d %H:%M')]"
          git push
