---
name: Continuous Test

on:
  push:
    branches:
      - 'main'
      - 'releases'
  pull_request: {}

jobs:
  lint:
    environment: continuous_test
    strategy:
      matrix:
        # Run for Python 3.8 only for now
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          pip install isort flake8 mypy interrogate dask distributed # Install manually dependencies (TODO: move to poetry)
          echo "## CI/CD Summary :rocket:" >> $GITHUB_STEP_SUMMARY
          echo "-------------------------" >> $GITHUB_STEP_SUMMARY
      - name: Check imports with isort
        run: |
          # Show the diffs for debugging
          isort -c dask_memusage_gpus/
          if [[ $? -ne 0 ]] ; then
              echo "* **isort results:**" >> $GITHUB_STEP_SUMMARY
              echo "```diff" >> $GITHUB_STEP_SUMMARY
              isort -c --df dask_memusage_gpus/ >> $GITHUB_STEP_SUMMARY
              echo "```" >> $GITHUB_STEP_SUMMARY
              exit 1
          else
              echo "* **isort results:** :white_check_mark:" >> $GITHUB_STEP_SUMMARY
              exit 0
          fi
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 dask_memusage_gpus/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 dask_memusage_gpus/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          if [[ $? -ne 0 ]] ; then
              echo "* **flake8 results:**" >> $GITHUB_STEP_SUMMARY
              echo "```python" >> $GITHUB_STEP_SUMMARY
              flake8 dask_memusage_gpus/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics >> $GITHUB_STEP_SUMMARY
              echo "```" >> $GITHUB_STEP_SUMMARY
              exit 1
          else
              echo "* **flake8 results:** :white_check_mark:" >> $GITHUB_STEP_SUMMARY
              exit 0
          fi
      - name: Lint with mypy
        run: |
          echo "* **Mypy results:** $(mypy dask_memusage_gpus/)" >> $GITHUB_STEP_SUMMARY
          mypy --install-types --non-interactive
          mypy dask_memusage_gpus/
      - name: Doc lint with interrogate
        run: |
          echo "* **interrogate results:** $(interrogate -i --fail-under=15 dask_memusage_gpus/ | cut -d: -d" " -f4)" >> $GITHUB_STEP_SUMMARY
          # We should have at least 80% of docs covered
          interrogate -vv -i --fail-under=90 -g /tmp/ -e build/ -e tests/

  tests:
    strategy:
      matrix:
        # Run for Python 3.8 only for now
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    environment: continuous_test
    needs: [lint]
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          python3 -m pip install pytest pytest-coverage coverage-badge mock parameterized distributed dask pandas pyarrow lxml xlsxwriter openpyxl
      - name: Run test cases
        run: |
          pytest --cov dask_memusage_gpus/ --cov-report xml:xml/coverage.xml tests/
      - name: Generate badge
        run: |
          coverage-badge -o /tmp/coverage.svg

  commit-badges-branch:
    runs-on: ubuntu-latest
    needs: [tests]
    if: github.ref == 'refs/heads/releases'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: badges
      - name: Setup Git
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
      - name: Update coverage
        id: coverage
        run: |
          if [ -f /tmp/coverage.svg ]; then
              mv /tmp/coverage.svg badges/
          else
              exit 1
          fi
      - name: Update interrogate
        id: interrogate
        run: |
          if [ -f /tmp/interrogate_badge.svg ]; then
              mv /tmp/interrogate_badge.svg badges/
          else
              exit 1
          fi
      - name: Commit & push data
        if: success() && (steps.coverage.outcome == 'success' || steps.interrogate.outcome == 'success')
        run: |
          git add -f badges/*
          git commit -m "Record badges [$(date +'%Y-%m-%d %H:%M')]"
          git push

  deploy:
    runs-on: ubuntu-latest
    environment: pypi_upload
    needs: [tests]
    if: github.ref == 'refs/heads/releases'
    steps:
      - uses: actions/checkout@v4
      - name: Generate artifacts
        run: |
          # Install twine and poetry
          pip install twine poetry
          poetry config virtualenvs.create false
          poetry build
      - name: Upload artifacts
        run: |
          twine upload --repository pypi dist/*
