name: PyPi Automatic Upload

on:
  workflow_run:
    workflows: Continuous Test
    branches: master
    types: completed

jobs:
  build:
    runs-on: ubuntu-latest
    environment: pypi_upload
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - name: Generate artifacts
        run: |
          # Install twine and poetry
          pip install twine poetry
          poetry config virtualenvs.create false
          poetry build
      - name: Upload artifacts
        run: |
          twine upload --repository pypi dist/*
